# You are given two strings s and t.
# String t is generated by random shuffling string s and then
# add one more letter at a random position.
# Return the letter that was added to t.
from collections import Counter


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s_dict = Counter(s)
        t_dict = Counter(t)

        for key, value in t_dict.items():
            if key not in s_dict or s_dict[key] < value:
                return key


obj = Solution()

s = "abcd"
t = "abcde"
print(obj.findTheDifference(s, t))  # Output: "e"
# Explanation: 'e' is the letter that was added.

s = ""
t = "y"
print(obj.findTheDifference(s, t))  # Output: "y"